#%RAML 1.0
title: Edge API - Orders
baseUri: https://github.com/folio-org/edge-orders
version: v2
documentation:
  - title: Edge API - Orders
    content: Edge API to interface with FOLIO for 3rd party purchasing systems for placing orders
types:
    orders: !include orders.xsd
/orders/validate:
  displayName: Validate
  get:
    description: Validate that the API Key provided can be used to place an order. The response body depends on the Vendor (GOBI or other)
    responses:
       200:
        description: Success
        body:
          application/xml:
            example: "<test>GET - OK</test>"
          application/json:
            example: "{test : POST - OK}"
       400:
        description: Bad Request.
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       401:
        description: Access Denied.
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       408:
        description: Request Timeout.
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       500:
        description: Internal Server Error.
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
    queryParameters:
      type:
        description: purchasing system type
        type: string
      apikey:
        description: API Key
        type: string
  post:
    description: Validate that the API Key provided can be used to place an order. The response body depends on the Vendor (GOBI or other)
    responses:
       200:
        description: Success
        body:
          application/xml:
            example: "<test>POST - OK</test>"
          application/json:
            example: "{test : POST - OK}"
       400:
        description: Bad Request
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       401:
        description: Access Denied
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       408:
        description: Request Timeout
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       500:
        description: Internal Server Error
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
    queryParameters:
      type:
        description: purchasing system type
        type: string
      apikey:
        description: API Key
        type: string
/orders:
  displayName: Place Order
  post:
    description: Place an order. The response body depends on the Vendor (GOBI or other)
     headers:
      Accept:
        displayName: Accept
        description: either application/xml or application/json
        type: string
        required: false
    responses:
       201:
        description: Success
        body:
          application/xml:
            type: string
          application/json:
            type: string
       400:
        description: Bad Request
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       401:
        description: Access Denied
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
             example: !include examples/error.json
       408:
        description: Request Timeout
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
            example: !include examples/error.json
       500:
        description: Internal Server Error
        body:
          application/xml:
            example: !include examples/error.xml
          application/json:
            example: !include examples/error.json
    queryParameters:
      type:
        description: purchasing system type
        type: string
      apikey:
        description: API Key
        type: string
/admin/health:
  displayName: Health Check
  get:
    description: Health Check
    responses:
      200:
        description: Success
        body:
          text/plain: null
